language: node_js
node_js:
  - '6'
  - '7'
install: npm install
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: build
      script: npm run build
    - stage: test
      script:
          - npm run test-with-coverage
          - npm run report-coverage
    - stage: lint
      script: npm run lint
