language: node_js
node_js:
  - '6'
  - '7'
install: npm install
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: Tests
      script: npm run build
    - script: npm run lint
    - script: npm run test-with-coverage
    - stage: Code Coverage
      script: npm run report-coverage
